function refPos = Poly5Position(t)    
    Tf = 1;
    posIni = 0; velIni = 0; accIni = 0;
    posFin = 1; velFin = 0; accFin = 0;
    %    
    A = [1,     0,      0,           0,           0,            0;...
         0,     1,      0,           0,           0,            0;...
         0,     0,      2,           0,           0,            0;...
         1,     Tf,     Tf.^2,       Tf.^3,       Tf.^4,        Tf.^5;...
         0,     1,      2*Tf,        3*Tf.^2,     4*Tf.^3,      5*Tf.^4;...
         0,     0,      2,           6*Tf,        12*Tf.^2,     20*Tf.^3];
    B = [posIni; velIni; accIni; posFin; velFin; accFin];
    coefs = A\B;
    refPos = coefs'*[1; t; t.^2; t.^3; t.^4; t.^5];
end