function joint11Rot = getJoint11Rotation(in1,in2)
%GETJOINT11ROTATION
%    JOINT11ROT = GETJOINT11ROTATION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:39:07

%======================================================================%
% Description: This function computes the rotation matrix of joint11
% joint11Rot = getJoint11Rotation(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% joint11Rot: Rotation matrix of the joint11 - 3x3 matrix
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
j11po = in1(13,:);
j11ro = in1(12,:);
j11yo = in1(14,:);
po = in2(5,:);
ro = in2(4,:);
yo = in2(6,:);
t2 = cos(j11ro);
t3 = sin(j11yo);
t4 = cos(j11yo);
t5 = sin(j11po);
t6 = sin(j11ro);
t7 = cos(po);
t8 = sin(po);
t9 = sin(yo);
t10 = cos(j11po);
t11 = cos(yo);
t12 = t2.*t3;
t13 = t4.*t5.*t6;
t14 = t12+t13;
t15 = sin(ro);
t16 = t3.*t6;
t30 = t2.*t4.*t5;
t17 = t16-t30;
t18 = cos(ro);
t19 = t2.*t4;
t31 = t3.*t5.*t6;
t20 = t19-t31;
t21 = t11.*t18;
t29 = t8.*t9.*t15;
t22 = t21-t29;
t23 = t4.*t6;
t24 = t2.*t3.*t5;
t25 = t23+t24;
t26 = t9.*t18;
t27 = t8.*t11.*t15;
t28 = t26+t27;
t32 = t11.*t15;
t33 = t8.*t9.*t18;
t34 = t32+t33;
t35 = t9.*t15;
t37 = t8.*t11.*t18;
t36 = t35-t37;
joint11Rot = reshape([t8.*t17-t7.*t9.*t14+t4.*t7.*t10.*t11,t14.*t22-t7.*t15.*t17+t4.*t10.*t28,t14.*t34+t7.*t17.*t18+t4.*t10.*t36,t8.*t25-t7.*t9.*t20-t3.*t7.*t10.*t11,t20.*t22-t3.*t10.*t28-t7.*t15.*t25,t20.*t34-t3.*t10.*t36+t7.*t18.*t25,t2.*t8.*t10+t5.*t7.*t11+t6.*t7.*t9.*t10,t5.*t28-t6.*t10.*t22-t2.*t7.*t10.*t15,t5.*t36-t6.*t10.*t34+t2.*t7.*t10.*t18],[3,3]);
