function link11PosJaco = getLink11PositionJacobian(in1,in2)
%GETLINK11POSITIONJACOBIAN
%    LINK11POSJACO = GETLINK11POSITIONJACOBIAN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:39:09

%======================================================================%
% Description: This function computes the position jacobian of the link11
% link11Pos = getLink11PositionJacobian(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% link11Pos: Position jacobian of the link11 - column vector
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
j11po = in1(13,:);
j11ro = in1(12,:);
j11xp = in1(9,:);
j11yo = in1(14,:);
j11yp = in1(10,:);
j11zp = in1(11,:);
l11xp = in1(15,:);
l11yp = in1(16,:);
l11zp = in1(17,:);
po = in2(5,:);
q11 = in2(7,:);
ro = in2(4,:);
yo = in2(6,:);
t2 = cos(po);
t3 = cos(j11po);
t4 = sin(po);
t5 = sin(j11ro);
t6 = cos(j11ro);
t7 = sin(j11po);
t8 = sin(yo);
t9 = sin(j11yo);
t10 = cos(j11yo);
t11 = cos(yo);
t12 = cos(q11);
t13 = t4.*t7.*t11;
t14 = t3.*t4.*t5.*t8;
t15 = t13+t14-t2.*t3.*t6;
t16 = sin(q11);
t17 = t5.*t9;
t32 = t6.*t7.*t10;
t18 = t17-t32;
t19 = t2.*t18;
t20 = t6.*t9;
t21 = t5.*t7.*t10;
t22 = t20+t21;
t23 = t4.*t8.*t22;
t24 = t19+t23-t3.*t4.*t10.*t11;
t25 = t2.*t7.*t8;
t26 = t25-t2.*t3.*t5.*t11;
t27 = t2.*t11.*t22;
t28 = t2.*t3.*t8.*t10;
t29 = t27+t28;
t30 = t6.*t10;
t40 = t5.*t7.*t9;
t31 = t30-t40;
t33 = t3.*t4.*t6;
t34 = t2.*t7.*t11;
t35 = t2.*t3.*t5.*t8;
t36 = t33+t34+t35;
t37 = t4.*t18;
t38 = t2.*t3.*t10.*t11;
t39 = t37+t38-t2.*t8.*t22;
t41 = cos(ro);
t42 = t5.*t10;
t43 = t6.*t7.*t9;
t44 = t42+t43;
t45 = sin(ro);
t46 = t8.*t45;
t51 = t4.*t11.*t41;
t47 = t46-t51;
t48 = t11.*t45;
t49 = t4.*t8.*t41;
t50 = t48+t49;
t52 = t7.*t47;
t53 = t2.*t3.*t6.*t41;
t102 = t3.*t5.*t50;
t54 = t52+t53-t102;
t55 = t22.*t50;
t56 = t2.*t18.*t41;
t57 = t3.*t10.*t47;
t58 = t55+t56+t57;
t59 = t4.*t18.*t45;
t60 = t2.*t3.*t10.*t11.*t45;
t61 = t59+t60-t2.*t8.*t22.*t45;
t62 = t3.*t4.*t6.*t45;
t63 = t2.*t7.*t11.*t45;
t64 = t2.*t3.*t5.*t8.*t45;
t65 = t62+t63+t64;
t66 = t8.*t41;
t67 = t4.*t11.*t45;
t68 = t66+t67;
t69 = t11.*t41;
t71 = t4.*t8.*t45;
t70 = t69-t71;
t72 = t22.*t68;
t73 = t72-t3.*t10.*t70;
t74 = t7.*t70;
t75 = t3.*t5.*t68;
t76 = t74+t75;
t77 = t3.*t5.*t70;
t78 = t2.*t3.*t6.*t45;
t83 = t7.*t68;
t79 = t77+t78-t83;
t80 = t22.*t70;
t81 = t3.*t10.*t68;
t85 = t2.*t18.*t45;
t82 = t80+t81-t85;
t84 = t16.*t79;
t86 = t12.*t82;
t87 = t84+t86;
t88 = t12.*t79;
t89 = t88-t16.*t82;
t90 = t3.*t4.*t6.*t41;
t91 = t2.*t7.*t11.*t41;
t92 = t2.*t3.*t5.*t8.*t41;
t93 = t90+t91+t92;
t94 = t4.*t18.*t41;
t95 = t2.*t3.*t10.*t11.*t41;
t96 = t94+t95-t2.*t8.*t22.*t41;
t97 = t22.*t47;
t98 = t97-t3.*t10.*t50;
t99 = t7.*t50;
t100 = t3.*t5.*t47;
t101 = t99+t100;
t103 = t12.*t54;
t104 = t16.*t58;
t105 = t103+t104;
t106 = t12.*t58;
link11PosJaco = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,-j11xp.*t47-j11yp.*t50-l11zp.*t105-l11xp.*(t106-t16.*t54)-l11yp.*(t31.*t50-t3.*t9.*t47+t2.*t41.*t44)-j11zp.*t2.*t41,j11xp.*t68+j11yp.*t70+l11xp.*t87-l11zp.*t89-l11yp.*(-t31.*t70+t3.*t9.*t68+t2.*t44.*t45)-j11zp.*t2.*t45,j11zp.*t2+l11yp.*(t2.*t44+t4.*t8.*t31+t3.*t4.*t9.*t11)+l11xp.*(t15.*t16+t12.*t24)-l11zp.*(t12.*t15-t16.*t24)+j11yp.*t4.*t8-j11xp.*t4.*t11,-l11yp.*(-t4.*t44.*t45+t2.*t8.*t31.*t45+t2.*t3.*t9.*t11.*t45)+l11xp.*(t12.*t61-t16.*t65)+l11zp.*(t12.*t65+t16.*t61)+j11zp.*t4.*t45-j11yp.*t2.*t8.*t45+j11xp.*t2.*t11.*t45,l11yp.*(-t4.*t41.*t44+t2.*t8.*t31.*t41+t2.*t3.*t9.*t11.*t41)-l11xp.*(t12.*t96-t16.*t93)-l11zp.*(t12.*t93+t16.*t96)-j11zp.*t4.*t41+j11yp.*t2.*t8.*t41-j11xp.*t2.*t11.*t41,-l11yp.*(t2.*t11.*t31-t2.*t3.*t8.*t9)-l11xp.*(t12.*t29-t16.*t26)-l11zp.*(t12.*t26+t16.*t29)-j11xp.*t2.*t8-j11yp.*t2.*t11,-l11yp.*(t31.*t68+t3.*t9.*t70)-j11yp.*t68+j11xp.*t70-l11xp.*(t12.*t73+t16.*t76)+l11zp.*(t12.*t76-t16.*t73),-l11yp.*(t31.*t47+t3.*t9.*t50)-j11yp.*t47+j11xp.*t50-l11xp.*(t12.*t98+t16.*t101)+l11zp.*(t12.*t101-t16.*t98),-l11xp.*(t12.*t36+t16.*t39)+l11zp.*(t12.*t39-t16.*t36),l11xp.*t89+l11zp.*t87,-l11xp.*t105+l11zp.*(t106-t16.*t54)],[3,7]);
