function link11Pos = getLink11Position(in1,in2)
%GETLINK11POSITION
%    LINK11POS = GETLINK11POSITION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:39:08

%======================================================================%
% Description: This function computes the position of the link11
% link11Pos = getLink11Position(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% link11Pos: Position of the link11 - column vector
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
j11po = in1(13,:);
j11ro = in1(12,:);
j11xp = in1(9,:);
j11yo = in1(14,:);
j11yp = in1(10,:);
j11zp = in1(11,:);
l11xp = in1(15,:);
l11yp = in1(16,:);
l11zp = in1(17,:);
po = in2(5,:);
px = in2(1,:);
py = in2(2,:);
pz = in2(3,:);
q11 = in2(7,:);
ro = in2(4,:);
yo = in2(6,:);
t2 = cos(j11po);
t3 = cos(po);
t4 = sin(po);
t5 = sin(j11ro);
t6 = cos(j11ro);
t7 = sin(j11po);
t8 = sin(yo);
t9 = sin(j11yo);
t10 = cos(j11yo);
t11 = cos(yo);
t12 = cos(q11);
t13 = t2.*t4.*t6;
t14 = t3.*t7.*t11;
t15 = t2.*t3.*t5.*t8;
t16 = t13+t14+t15;
t17 = sin(q11);
t18 = t5.*t9;
t39 = t6.*t7.*t10;
t19 = t18-t39;
t20 = t4.*t19;
t21 = t6.*t9;
t22 = t5.*t7.*t10;
t23 = t21+t22;
t24 = t2.*t3.*t10.*t11;
t25 = t20+t24-t3.*t8.*t23;
t26 = cos(ro);
t27 = sin(ro);
t28 = t6.*t10;
t46 = t5.*t7.*t9;
t29 = t28-t46;
t30 = t11.*t26;
t38 = t4.*t8.*t27;
t31 = t30-t38;
t32 = t5.*t10;
t33 = t6.*t7.*t9;
t34 = t32+t33;
t35 = t8.*t26;
t36 = t4.*t11.*t27;
t37 = t35+t36;
t40 = t2.*t5.*t31;
t41 = t2.*t3.*t6.*t27;
t42 = t40+t41-t7.*t37;
t43 = t23.*t31;
t44 = t2.*t10.*t37;
t45 = t43+t44-t3.*t19.*t27;
t47 = t8.*t27;
t52 = t4.*t11.*t26;
t48 = t47-t52;
t49 = t11.*t27;
t50 = t4.*t8.*t26;
t51 = t49+t50;
t53 = t7.*t48;
t54 = t2.*t3.*t6.*t26;
t55 = t53+t54-t2.*t5.*t51;
t56 = t23.*t51;
t57 = t3.*t19.*t26;
t58 = t2.*t10.*t48;
t59 = t56+t57+t58;
link11Pos = [px+j11zp.*t4-l11yp.*(-t4.*t34+t3.*t8.*t29+t2.*t3.*t9.*t11)-l11xp.*(t16.*t17-t12.*t25)+l11zp.*(t12.*t16+t17.*t25)-j11yp.*t3.*t8+j11xp.*t3.*t11;py+j11yp.*t31+j11xp.*t37+l11xp.*(t12.*t45+t17.*t42)-l11zp.*(t12.*t42-t17.*t45)-l11yp.*(-t29.*t31+t2.*t9.*t37+t3.*t27.*t34)-j11zp.*t3.*t27;pz+j11xp.*t48+j11yp.*t51+l11xp.*(t12.*t59-t17.*t55)+l11zp.*(t12.*t55+t17.*t59)+l11yp.*(t29.*t51-t2.*t9.*t48+t3.*t26.*t34)+j11zp.*t3.*t26];
