function link11Rot = getLink11Rotation(in1,in2)
%GETLINK11ROTATION
%    LINK11ROT = GETLINK11ROTATION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:39:13

%======================================================================%
% Description: This function computes the rotation matrix of the link11
% link11Rot = getLink11Rotation(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% link11Rot: Rotation matrix of the link11 - 3x3 matrix
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
j11po = in1(13,:);
j11ro = in1(12,:);
j11yo = in1(14,:);
l11po = in1(19,:);
l11ro = in1(18,:);
l11yo = in1(20,:);
po = in2(5,:);
q11 = in2(7,:);
ro = in2(4,:);
yo = in2(6,:);
t2 = cos(j11ro);
t3 = sin(j11yo);
t4 = cos(j11yo);
t5 = sin(j11po);
t6 = sin(j11ro);
t7 = cos(po);
t8 = sin(po);
t9 = sin(yo);
t10 = cos(j11po);
t11 = cos(yo);
t12 = cos(l11po);
t13 = sin(l11ro);
t14 = cos(l11ro);
t15 = sin(l11po);
t16 = t2.*t8.*t10;
t17 = t5.*t7.*t11;
t18 = t6.*t7.*t9.*t10;
t19 = t16+t17+t18;
t20 = sin(l11yo);
t21 = cos(l11yo);
t22 = t4.*t6;
t23 = t2.*t3.*t5;
t24 = t22+t23;
t25 = t2.*t4;
t39 = t3.*t5.*t6;
t26 = t25-t39;
t27 = t7.*t9.*t26;
t28 = t3.*t7.*t10.*t11;
t38 = t8.*t24;
t29 = t27+t28-t38;
t30 = t3.*t6;
t40 = t2.*t4.*t5;
t31 = t30-t40;
t32 = t8.*t31;
t33 = t2.*t3;
t34 = t4.*t5.*t6;
t35 = t33+t34;
t36 = t4.*t7.*t10.*t11;
t41 = t7.*t9.*t35;
t37 = t32+t36-t41;
t42 = cos(q11);
t43 = t15.*t37;
t44 = t12.*t13.*t29;
t45 = t12.*t14.*t19;
t46 = t43+t44+t45;
t47 = sin(q11);
t48 = t13.*t20;
t64 = t14.*t15.*t21;
t49 = t48-t64;
t50 = t19.*t49;
t51 = t14.*t20;
t52 = t13.*t15.*t21;
t53 = t51+t52;
t54 = t12.*t21.*t37;
t55 = t50+t54-t29.*t53;
t56 = sin(ro);
t57 = cos(ro);
t58 = t9.*t57;
t59 = t8.*t11.*t56;
t60 = t58+t59;
t61 = t11.*t57;
t63 = t8.*t9.*t56;
t62 = t61-t63;
t65 = t6.*t10.*t62;
t66 = t2.*t7.*t10.*t56;
t77 = t5.*t60;
t67 = t65+t66-t77;
t68 = t7.*t24.*t56;
t69 = t3.*t10.*t60;
t80 = t26.*t62;
t70 = t68+t69-t80;
t71 = t35.*t62;
t72 = t4.*t10.*t60;
t81 = t7.*t31.*t56;
t73 = t71+t72-t81;
t74 = t13.*t21;
t75 = t14.*t15.*t20;
t76 = t74+t75;
t78 = t14.*t21;
t105 = t13.*t15.*t20;
t79 = t78-t105;
t82 = t15.*t73;
t83 = t12.*t13.*t70;
t84 = t82+t83-t12.*t14.*t67;
t85 = t49.*t67;
t86 = t53.*t70;
t87 = t85+t86-t12.*t21.*t73;
t88 = t9.*t56;
t93 = t8.*t11.*t57;
t89 = t88-t93;
t90 = t11.*t56;
t91 = t8.*t9.*t57;
t92 = t90+t91;
t94 = t5.*t89;
t95 = t2.*t7.*t10.*t57;
t104 = t6.*t10.*t92;
t96 = t94+t95-t104;
t97 = t26.*t92;
t98 = t7.*t24.*t57;
t106 = t3.*t10.*t89;
t99 = t97+t98-t106;
t100 = t35.*t92;
t101 = t7.*t31.*t57;
t102 = t4.*t10.*t89;
t103 = t100+t101+t102;
t107 = t15.*t103;
t108 = t12.*t14.*t96;
t109 = t107+t108-t12.*t13.*t99;
t110 = t49.*t96;
t111 = t53.*t99;
t112 = t12.*t21.*t103;
t113 = t110+t111+t112;
link11Rot = reshape([-t46.*t47+t42.*t55,-t42.*t87-t47.*t84,t42.*t113-t47.*t109,t19.*t76-t29.*t79-t12.*t20.*t37,-t67.*t76-t70.*t79-t12.*t20.*t73,t76.*t96+t79.*t99-t12.*t20.*t103,t42.*t46+t47.*t55,t42.*t84-t47.*t87,t42.*t109+t47.*t113],[3,3]);
