function symFixedBaseLegModelParams = getFixedBaseLegModelPhysicalParams(g, L1, L2, L3, l1, l2, l3, m1, m2, m3)
    %% Joints
    % Joint1    
    joint(1).origin.xyz = [0; 0; 0];
    joint(1).origin.rpy = [0; 0; 0];    
    % Joint2    
    joint(2).origin.xyz = [0; 0; L1];
    joint(2).origin.rpy = [0; 0; 0];    
    % Joint3    
    joint(3).origin.xyz = [0; 0; L2];
    joint(3).origin.rpy = [0; 0; 0];    
    
    %% Links
    % Link1    
    link(1).origin.xyz = [0; 0; l1];
    link(1).origin.rpy = [0; 0; 0];
    link(1).mass = m1;
    link(1).inertia = [(1/12)*m1*L1^2, 0,                   0;...
                       0,              (1/12)*m1*L1^2,      0;...
                       0,              0,                   0];
    % Link2    
    link(2).origin.xyz = [0; 0; l2];
    link(2).origin.rpy = [0; 0; 0];
    link(2).mass = m2;
    link(2).inertia = [(1/12)*m2*L2^2, 0,                   0;...
                       0,              (1/12)*m2*L2^2,      0;...
                       0,              0,                   0];
                   
    % Link3    
    link(3).origin.xyz = [l3; 0; 0];
    link(3).origin.rpy = [0; 0; 0];
    link(3).mass = m3;
    link(3).inertia = [0,              0,                   0;...
                       0,              (1/12)*m1*L3^2,      0;...
                       0,              0,                   (1/12)*m1*L3^2];


%%
symJointPhysicalParams = [joint(1).origin.xyz;...
                          joint(1).origin.rpy;...
                          joint(2).origin.xyz;...
                          joint(2).origin.rpy;...
                          joint(3).origin.xyz;...
                          joint(3).origin.rpy];
symLinkPhysicalParams = [link(1).origin.xyz;...
                         link(1).origin.rpy;...
                         link(1).mass;...
                         link(1).inertia(1, 1);...
                         link(1).inertia(1, 2);...
                         link(1).inertia(1, 3);...
                         link(1).inertia(2, 2);...
                         link(1).inertia(2, 3);...
                         link(1).inertia(3, 3);...
                         link(2).origin.xyz;...
                         link(2).origin.rpy;...
                         link(2).mass;...
                         link(2).inertia(1, 1);...
                         link(2).inertia(1, 2);...
                         link(2).inertia(1, 3);...
                         link(2).inertia(2, 2);...
                         link(2).inertia(2, 3);...
                         link(2).inertia(3, 3);...
                         link(3).origin.xyz;...
                         link(3).origin.rpy;...
                         link(3).mass;...
                         link(3).inertia(1, 1);...
                         link(3).inertia(1, 2);...
                         link(3).inertia(1, 3);...
                         link(3).inertia(2, 2);...
                         link(3).inertia(2, 3);...
                         link(3).inertia(3, 3)];

symFixedBaseLegModelParams = [g; symJointPhysicalParams; symLinkPhysicalParams];
end