function joint11PosJaco = getJoint11PositionJacobian(in1,in2)
%GETJOINT11POSITIONJACOBIAN
%    JOINT11POSJACO = GETJOINT11POSITIONJACOBIAN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Sep-2018 18:20:57

%======================================================================%
% Description: This function computes the position jacobian of joint11
% joint11PosJaco = getJoint11PositionJacobian(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% joint11PosJaco: Position jacobian of the joint11 - column vector
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
joint11PosJaco = sparse([],[],[],3,2);
