function joint12Rot = getJoint12Rotation(in1,in2)
%GETJOINT12ROTATION
%    JOINT12ROT = GETJOINT12ROTATION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Sep-2018 18:21:00

%======================================================================%
% Description: This function computes the rotation matrix of joint12
% joint12Rot = getJoint12Rotation(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% joint12Rot: Rotation matrix of the joint12 - 3x3 matrix
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
j11po = in1(6,:);
j11ro = in1(5,:);
j11yo = in1(7,:);
q11 = in2(1,:);
t2 = sparse(sin(j11po));
t3 = sparse(cos(j11po));
t4 = sparse(cos(j11yo));
t5 = sparse(sin(j11yo));
t6 = sparse(cos(j11ro));
t7 = sparse(sin(j11ro));
t8 = sparse(t3.^2);
t9 = sparse(sin(q11));
t10 = sparse(t5.*t7);
t26 = sparse(t2.*t4.*t6);
t11 = sparse(t10-t26);
t12 = sparse(t2.*t11);
t13 = sparse(t4.^2);
t14 = sparse(t8.*t13);
t15 = sparse(t5.*t6);
t16 = sparse(t2.*t4.*t7);
t17 = sparse(t15+t16);
t31 = sparse(t3.*t5.*t17);
t18 = sparse(t12+t14-t31);
t19 = sparse(cos(q11));
t20 = sparse(t5.*t7.*t8);
t21 = sparse(t2.*t3.*t6);
t22 = sparse(t2.*t3.*t4);
t23 = sparse(t20+t21+t22);
t24 = sparse(t4.*t6);
t27 = sparse(t2.*t5.*t7);
t25 = sparse(t24-t27);
t28 = sparse(t4.*t7);
t29 = sparse(t2.*t5.*t6);
t30 = sparse(t28+t29);
t32 = sparse(t17.*t25);
t33 = sparse(t3.*t4.*t17);
t34 = sparse(t32+t33-t3.*t7.*t11);
t35 = sparse(t6.*t7.*t8);
t36 = sparse(t3.*t7.*t25);
t37 = sparse(t35+t36-t2.*t17);
t38 = sparse(t6.^2);
t39 = sparse(t8.*t38);
t40 = sparse(t12+t39-t3.*t7.*t30);
t41 = sparse(t17.*t30);
t42 = sparse(t3.*t6.*t11);
t43 = sparse(t3.*t4.*t11);
t44 = sparse(t41+t42+t43);
joint12Rot = sparse([1,2,3,1,2,3,1,2,3],[1,1,1,2,2,2,3,3,3],[-t9.*t23+t18.*t19,t9.*t37+t19.*t34,-t9.*t40+t19.*t44,t2.*t30-t4.*t5.*t8-t3.*t5.*t25,-t31+t25.^2-t3.*t7.*t30,t25.*t30-t3.*t5.*t11+t3.*t6.*t30,t9.*t18+t19.*t23,t9.*t34-t19.*t37,t9.*t44+t19.*t40],3,3);
