function joint11Vel = getJoint11Velocity(in1,in2)
%GETJOINT11VELOCITY
%    JOINT11VEL = GETJOINT11VELOCITY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Sep-2018 18:20:57

%======================================================================%
% Description: This function computes the velocity of joint11
% joint11Vel = getJoint11Velocity(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% joint11Vel: Velocity of the joint11 - column vector
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
joint11Vel = sparse([],[],[],3,1);
