function link12Pos = getLink12Position(in1,in2)
%GETLINK12POSITION
%    LINK12POS = GETLINK12POSITION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Sep-2018 18:21:02

%======================================================================%
% Description: This function computes the position of the link12
% link12Pos = getLink12Position(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% link12Pos: Position of the link12 - column vector
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
j11po = in1(6,:);
j11ro = in1(5,:);
j11xp = in1(2,:);
j11yo = in1(7,:);
j11yp = in1(3,:);
j12xp = in1(8,:);
j11zp = in1(4,:);
j12yp = in1(9,:);
j12zp = in1(10,:);
l12po = in1(31,:);
l12ro = in1(30,:);
l12xp = in1(27,:);
l12yo = in1(32,:);
l12yp = in1(28,:);
l12zp = in1(29,:);
q11 = in2(1,:);
q12 = in2(2,:);
t2 = sparse(cos(q11));
t3 = sparse(sin(j11po));
t4 = sparse(cos(j11po));
t5 = sparse(cos(j11yo));
t6 = sparse(sin(q11));
t7 = sparse(sin(j11yo));
t8 = sparse(cos(j11ro));
t9 = sparse(sin(j11ro));
t10 = sparse(t4.^2);
t11 = sparse(cos(l12yo));
t12 = sparse(sin(l12ro));
t13 = sparse(cos(l12ro));
t14 = sparse(sin(l12po));
t15 = sparse(sin(l12yo));
t16 = sparse(t7.*t9);
t29 = sparse(t3.*t5.*t8);
t17 = sparse(t16-t29);
t18 = sparse(t3.*t17);
t19 = sparse(t5.^2);
t20 = sparse(t10.*t19);
t21 = sparse(t7.*t8);
t22 = sparse(t3.*t5.*t9);
t23 = sparse(t21+t22);
t30 = sparse(t4.*t7.*t23);
t24 = sparse(t18+t20-t30);
t25 = sparse(t7.*t9.*t10);
t26 = sparse(t3.*t4.*t8);
t27 = sparse(t3.*t4.*t5);
t28 = sparse(t25+t26+t27);
t31 = sparse(t2.*t24);
t47 = sparse(t6.*t28);
t32 = sparse(t31-t47);
t33 = sparse(cos(l12po));
t34 = sparse(t6.*t24);
t35 = sparse(t2.*t28);
t36 = sparse(t34+t35);
t37 = sparse(t5.*t9);
t38 = sparse(t3.*t7.*t8);
t39 = sparse(t37+t38);
t40 = sparse(t5.*t7.*t10);
t41 = sparse(t5.*t8);
t46 = sparse(t3.*t7.*t9);
t42 = sparse(t41-t46);
t43 = sparse(t4.*t7.*t42);
t45 = sparse(t3.*t39);
t44 = sparse(t40+t43-t45);
t48 = sparse(cos(q12));
t49 = sparse(t14.*t32);
t50 = sparse(t13.*t33.*t36);
t51 = sparse(t12.*t33.*t44);
t52 = sparse(t49+t50+t51);
t53 = sparse(sin(q12));
t54 = sparse(t13.*t15);
t55 = sparse(t11.*t12.*t14);
t56 = sparse(t54+t55);
t57 = sparse(t12.*t15);
t83 = sparse(t11.*t13.*t14);
t58 = sparse(t57-t83);
t59 = sparse(t36.*t58);
t60 = sparse(t11.*t32.*t33);
t61 = sparse(t59+t60-t44.*t56);
t62 = sparse(t11.*t12);
t63 = sparse(t13.*t14.*t15);
t64 = sparse(t62+t63);
t65 = sparse(t11.*t13);
t91 = sparse(t12.*t14.*t15);
t66 = sparse(t65-t91);
t67 = sparse(t23.*t42);
t68 = sparse(t4.*t5.*t23);
t73 = sparse(t4.*t9.*t17);
t69 = sparse(t67+t68-t73);
t70 = sparse(t8.*t9.*t10);
t71 = sparse(t4.*t9.*t42);
t75 = sparse(t3.*t23);
t72 = sparse(t70+t71-t75);
t74 = sparse(t2.*t69);
t76 = sparse(t6.*t72);
t77 = sparse(t74+t76);
t78 = sparse(t42.^2);
t79 = sparse(t4.*t9.*t39);
t80 = sparse(t30-t78+t79);
t81 = sparse(t2.*t72);
t84 = sparse(t6.*t69);
t82 = sparse(t81-t84);
t85 = sparse(t14.*t77);
t86 = sparse(t12.*t33.*t80);
t87 = sparse(t85+t86-t13.*t33.*t82);
t88 = sparse(t58.*t82);
t89 = sparse(t56.*t80);
t90 = sparse(t88+t89-t11.*t33.*t77);
t92 = sparse(t23.*t39);
t93 = sparse(t4.*t8.*t17);
t94 = sparse(t4.*t5.*t17);
t95 = sparse(t92+t93+t94);
t96 = sparse(t8.^2);
t97 = sparse(t10.*t96);
t98 = sparse(t18-t79+t97);
t99 = sparse(t2.*t95);
t108 = sparse(t6.*t98);
t100 = sparse(t99-t108);
t101 = sparse(t39.*t42);
t102 = sparse(t4.*t8.*t39);
t107 = sparse(t4.*t7.*t17);
t103 = sparse(t101+t102-t107);
t104 = sparse(t2.*t98);
t105 = sparse(t6.*t95);
t106 = sparse(t104+t105);
t109 = sparse(t14.*t100);
t110 = sparse(t13.*t33.*t106);
t111 = sparse(t109+t110-t12.*t33.*t103);
t112 = sparse(t58.*t106);
t113 = sparse(t56.*t103);
t114 = sparse(t11.*t33.*t100);
t115 = sparse(t112+t113+t114);
link12Pos = sparse([1,2,3],[1,1,1],[j11xp-j12xp.*(t3.*t6-t2.*t4.*t5)+j12zp.*(t2.*t3+t4.*t5.*t6)-l12yp.*(-t36.*t64+t44.*t66+t15.*t32.*t33)-l12xp.*(t52.*t53-t48.*t61)+l12zp.*(t48.*t52+t53.*t61)-j12yp.*t4.*t7,j11yp+j12xp.*(t2.*t23+t4.*t6.*t9)+j12zp.*(t6.*t23-t2.*t4.*t9)+j12yp.*t42-l12yp.*(t64.*t82+t66.*t80+t15.*t33.*t77)-l12xp.*(t48.*t90+t53.*t87)+l12zp.*(t48.*t87-t53.*t90),j11zp+j12xp.*(t2.*t17-t4.*t6.*t8)+j12zp.*(t6.*t17+t2.*t4.*t8)+j12yp.*t39+l12yp.*(t66.*t103+t64.*t106-t15.*t33.*t100)+l12xp.*(t48.*t115-t53.*t111)+l12zp.*(t48.*t111+t53.*t115)],3,1);
