function link12Vel = getLink12Velocity(in1,in2)
%GETLINK12VELOCITY
%    LINK12VEL = GETLINK12VELOCITY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Sep-2018 18:21:09

%======================================================================%
% Description: This function computes the velocity of the link12
% link12Vel = getLink12Velocity(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% link12Vel: Velocity of the link12 - column vector
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
dq11 = in2(3,:);
dq12 = in2(4,:);
j11po = in1(6,:);
j11ro = in1(5,:);
j11yo = in1(7,:);
j12xp = in1(8,:);
j12zp = in1(10,:);
l12po = in1(31,:);
l12ro = in1(30,:);
l12xp = in1(27,:);
l12yo = in1(32,:);
l12yp = in1(28,:);
l12zp = in1(29,:);
q11 = in2(1,:);
q12 = in2(2,:);
t2 = sparse(sin(j11po));
t3 = sparse(cos(j11po));
t4 = sparse(cos(j11yo));
t5 = sparse(sin(j11yo));
t6 = sparse(cos(j11ro));
t7 = sparse(sin(j11ro));
t8 = sparse(t3.^2);
t9 = sparse(cos(q11));
t10 = sparse(t5.*t7);
t24 = sparse(t2.*t4.*t6);
t11 = sparse(t10-t24);
t12 = sparse(t2.*t11);
t13 = sparse(t4.^2);
t14 = sparse(t8.*t13);
t15 = sparse(t5.*t6);
t16 = sparse(t2.*t4.*t7);
t17 = sparse(t15+t16);
t25 = sparse(t3.*t5.*t17);
t18 = sparse(t12+t14-t25);
t19 = sparse(sin(q11));
t20 = sparse(t5.*t7.*t8);
t21 = sparse(t2.*t3.*t6);
t22 = sparse(t2.*t3.*t4);
t23 = sparse(t20+t21+t22);
t26 = sparse(t9.*t18);
t37 = sparse(t19.*t23);
t27 = sparse(t26-t37);
t28 = sparse(cos(l12ro));
t29 = sparse(sin(l12po));
t30 = sparse(cos(l12po));
t31 = sparse(cos(l12yo));
t32 = sparse(t18.*t19);
t33 = sparse(t9.*t23);
t34 = sparse(t32+t33);
t35 = sparse(cos(q12));
t36 = sparse(t29.*t34);
t38 = sparse(t36-t27.*t28.*t30);
t39 = sparse(sin(q12));
t40 = sparse(sin(l12ro));
t41 = sparse(sin(l12yo));
t42 = sparse(t40.*t41);
t54 = sparse(t28.*t29.*t31);
t43 = sparse(t42-t54);
t44 = sparse(t27.*t43);
t45 = sparse(t44-t30.*t31.*t34);
t46 = sparse(t4.*t7);
t47 = sparse(t2.*t5.*t6);
t48 = sparse(t46+t47);
t49 = sparse(t4.*t5.*t8);
t50 = sparse(t4.*t6);
t58 = sparse(t2.*t5.*t7);
t51 = sparse(t50-t58);
t52 = sparse(t3.*t5.*t51);
t57 = sparse(t2.*t48);
t53 = sparse(t49+t52-t57);
t55 = sparse(t27.*t29);
t56 = sparse(t28.*t30.*t34);
t59 = sparse(t30.*t40.*t53);
t60 = sparse(t55+t56+t59);
t61 = sparse(t28.*t41);
t62 = sparse(t29.*t31.*t40);
t63 = sparse(t61+t62);
t64 = sparse(t34.*t43);
t65 = sparse(t27.*t30.*t31);
t66 = sparse(t64+t65-t53.*t63);
t67 = sparse(t17.*t51);
t68 = sparse(t3.*t4.*t17);
t73 = sparse(t3.*t7.*t11);
t69 = sparse(t67+t68-t73);
t70 = sparse(t6.*t7.*t8);
t71 = sparse(t3.*t7.*t51);
t74 = sparse(t2.*t17);
t72 = sparse(t70+t71-t74);
t75 = sparse(t9.*t72);
t85 = sparse(t19.*t69);
t76 = sparse(t75-t85);
t77 = sparse(t51.^2);
t78 = sparse(t3.*t7.*t48);
t79 = sparse(t25-t77+t78);
t80 = sparse(t9.*t69);
t81 = sparse(t19.*t72);
t82 = sparse(t80+t81);
t83 = sparse(t29.*t82);
t84 = sparse(t30.*t40.*t79);
t86 = sparse(t83+t84-t28.*t30.*t76);
t87 = sparse(t43.*t76);
t88 = sparse(t63.*t79);
t89 = sparse(t87+t88-t30.*t31.*t82);
t90 = sparse(t31.*t40);
t91 = sparse(t28.*t29.*t41);
t92 = sparse(t90+t91);
t93 = sparse(t43.*t82);
t94 = sparse(t29.*t76);
t95 = sparse(t28.*t30.*t82);
t96 = sparse(t6.^2);
t97 = sparse(t8.*t96);
t98 = sparse(t12-t78+t97);
t99 = sparse(t17.*t48);
t100 = sparse(t3.*t6.*t11);
t101 = sparse(t3.*t4.*t11);
t102 = sparse(t99+t100+t101);
t103 = sparse(t9.*t98);
t104 = sparse(t19.*t102);
t105 = sparse(t103+t104);
t106 = sparse(t9.*t102);
t108 = sparse(t19.*t98);
t107 = sparse(t106-t108);
t109 = sparse(t43.*t107);
t110 = sparse(t109-t30.*t31.*t105);
t111 = sparse(t29.*t105);
t112 = sparse(t111-t28.*t30.*t107);
t113 = sparse(t48.*t51);
t114 = sparse(t3.*t6.*t48);
t117 = sparse(t3.*t5.*t11);
t115 = sparse(t113+t114-t117);
t116 = sparse(t29.*t107);
t118 = sparse(t28.*t30.*t105);
t119 = sparse(t116+t118-t30.*t40.*t115);
t120 = sparse(t43.*t105);
t121 = sparse(t63.*t115);
t122 = sparse(t30.*t31.*t107);
t123 = sparse(t120+t121+t122);
link12Vel = sparse([1,2,3],[1,1,1],[-dq11.*(j12xp.*(t2.*t9+t3.*t4.*t19)+j12zp.*(t2.*t19-t3.*t4.*t9)-l12yp.*(t27.*t92+t30.*t34.*t41)-l12xp.*(t38.*t39+t35.*t45)+l12zp.*(t35.*t38-t39.*t45))-dq12.*(l12xp.*(t35.*t60+t39.*t66)+l12zp.*(t39.*t60-t35.*t66)),dq11.*(-j12xp.*(t17.*t19-t3.*t7.*t9)+j12zp.*(t9.*t17+t3.*t7.*t19)+l12yp.*(t82.*t92-t30.*t41.*t76)-l12xp.*(t39.*(t94+t95)-t35.*(t93+t30.*t31.*t76))+l12zp.*(t35.*(t94+t95)+t39.*(t93+t30.*t31.*(t75-t85))))-dq12.*(l12xp.*(t35.*t86-t39.*t89)+l12zp.*(t35.*t89+t39.*t86)),dq11.*(-j12xp.*(t11.*t19+t3.*t6.*t9)+j12zp.*(t9.*t11-t3.*t6.*t19)+l12yp.*(t92.*t107+t30.*t41.*t105)+l12xp.*(t35.*t110+t39.*t112)-l12zp.*(t35.*t112-t39.*t110))-dq12.*(l12xp.*(t35.*t119+t39.*t123)-l12zp.*(t35.*t123-t39.*t119))],3,1);
