function joint12Rot = getJoint12Rotation(in1,in2)
%GETJOINT12ROTATION
%    JOINT12ROT = GETJOINT12ROTATION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:43:15

%======================================================================%
% Description: This function computes the rotation matrix of joint12
% joint12Rot = getJoint12Rotation(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% joint12Rot: Rotation matrix of the joint12 - 3x3 matrix
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
j11po = in1(6,:);
j11ro = in1(5,:);
j11yo = in1(7,:);
q11 = in2(1,:);
t2 = sin(j11po);
t3 = cos(j11po);
t4 = cos(j11yo);
t5 = sin(j11yo);
t6 = cos(j11ro);
t7 = sin(j11ro);
t8 = t3.^2;
t9 = sin(q11);
t10 = t5.*t7;
t26 = t2.*t4.*t6;
t11 = t10-t26;
t12 = t2.*t11;
t13 = t4.^2;
t14 = t8.*t13;
t15 = t5.*t6;
t16 = t2.*t4.*t7;
t17 = t15+t16;
t31 = t3.*t5.*t17;
t18 = t12+t14-t31;
t19 = cos(q11);
t20 = t5.*t7.*t8;
t21 = t2.*t3.*t6;
t22 = t2.*t3.*t4;
t23 = t20+t21+t22;
t24 = t4.*t6;
t27 = t2.*t5.*t7;
t25 = t24-t27;
t28 = t4.*t7;
t29 = t2.*t5.*t6;
t30 = t28+t29;
t32 = t17.*t25;
t33 = t3.*t4.*t17;
t34 = t32+t33-t3.*t7.*t11;
t35 = t6.*t7.*t8;
t36 = t3.*t7.*t25;
t37 = t35+t36-t2.*t17;
t38 = t6.^2;
t39 = t8.*t38;
t40 = t12+t39-t3.*t7.*t30;
t41 = t17.*t30;
t42 = t3.*t6.*t11;
t43 = t3.*t4.*t11;
t44 = t41+t42+t43;
joint12Rot = reshape([-t9.*t23+t18.*t19,t9.*t37+t19.*t34,-t9.*t40+t19.*t44,t2.*t30-t4.*t5.*t8-t3.*t5.*t25,-t31+t25.^2-t3.*t7.*t30,t25.*t30-t3.*t5.*t11+t3.*t6.*t30,t9.*t18+t19.*t23,t9.*t34-t19.*t37,t9.*t44+t19.*t40],[3,3]);
