function joint13Vel = getJoint13Velocity(in1,in2)
%GETJOINT13VELOCITY
%    JOINT13VEL = GETJOINT13VELOCITY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:43:30

%======================================================================%
% Description: This function computes the velocity of joint13
% joint13Vel = getJoint13Velocity(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% joint13Vel: Velocity of the joint13 - column vector
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
dq11 = in2(4,:);
dq12 = in2(5,:);
j11po = in1(6,:);
j11ro = in1(5,:);
j11yo = in1(7,:);
j12xp = in1(8,:);
j13xp = in1(14,:);
j12zp = in1(10,:);
j13zp = in1(16,:);
q11 = in2(1,:);
q12 = in2(2,:);
t2 = sin(j11po);
t3 = cos(j11po);
t4 = cos(j11yo);
t5 = sin(j11yo);
t6 = cos(j11ro);
t7 = sin(j11ro);
t8 = t3.^2;
t9 = cos(q11);
t10 = t5.*t7;
t25 = t2.*t4.*t6;
t11 = t10-t25;
t12 = t2.*t11;
t13 = t4.^2;
t14 = t8.*t13;
t15 = t5.*t6;
t16 = t2.*t4.*t7;
t17 = t15+t16;
t26 = t3.*t5.*t17;
t18 = t12+t14-t26;
t19 = sin(q11);
t20 = t5.*t7.*t8;
t21 = t2.*t3.*t6;
t22 = t2.*t3.*t4;
t23 = t20+t21+t22;
t24 = cos(q12);
t27 = t9.*t18;
t34 = t19.*t23;
t28 = t27-t34;
t29 = sin(q12);
t30 = t18.*t19;
t31 = t9.*t23;
t32 = t30+t31;
t33 = t24.*t32;
t35 = t28.*t29;
t36 = t33+t35;
t37 = j13xp.*t36;
t38 = t24.*t28;
t39 = t38-t29.*t32;
t40 = t4.*t6;
t42 = t2.*t5.*t7;
t41 = t40-t42;
t43 = t17.*t41;
t44 = t3.*t4.*t17;
t49 = t3.*t7.*t11;
t45 = t43+t44-t49;
t46 = t6.*t7.*t8;
t47 = t3.*t7.*t41;
t51 = t2.*t17;
t48 = t46+t47-t51;
t50 = t9.*t45;
t52 = t19.*t48;
t53 = t50+t52;
t54 = t9.*t48;
t56 = t19.*t45;
t55 = t54-t56;
t57 = t24.*t55;
t58 = t57-t29.*t53;
t59 = j13xp.*t58;
t60 = t24.*t53;
t61 = t29.*t55;
t62 = t60+t61;
t63 = j13zp.*t62;
t64 = t4.*t7;
t65 = t2.*t5.*t6;
t66 = t64+t65;
t67 = t17.*t66;
t68 = t3.*t6.*t11;
t69 = t3.*t4.*t11;
t70 = t67+t68+t69;
t71 = t6.^2;
t72 = t8.*t71;
t75 = t3.*t7.*t66;
t73 = t12+t72-t75;
t74 = t9.*t70;
t81 = t19.*t73;
t76 = t74-t81;
t77 = t9.*t73;
t78 = t19.*t70;
t79 = t77+t78;
t80 = t24.*t79;
t82 = t29.*t76;
t83 = t80+t82;
t84 = j13xp.*t83;
t85 = t24.*t76;
t86 = t85-t29.*t79;
joint13Vel = [-dq11.*(t37+j12xp.*(t2.*t9+t3.*t4.*t19)+j12zp.*(t2.*t19-t3.*t4.*t9)-j13zp.*t39)-dq12.*(t37-j13zp.*t39);dq12.*(t59+t63)+dq11.*(t59+t63-j12xp.*(t17.*t19-t3.*t7.*t9)+j12zp.*(t9.*t17+t3.*t7.*t19));-dq11.*(t84+j12xp.*(t11.*t19+t3.*t6.*t9)-j12zp.*(t9.*t11-t3.*t6.*t19)-j13zp.*t86)-dq12.*(t84-j13zp.*t86)];
