function joint13PosJaco = getJoint13PositionJacobian(in1,in2)
%GETJOINT13POSITIONJACOBIAN
%    JOINT13POSJACO = GETJOINT13POSITIONJACOBIAN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:43:29

%======================================================================%
% Description: This function computes the position jacobian of joint13
% joint13PosJaco = getJoint13PositionJacobian(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% joint13PosJaco: Position jacobian of the joint13 - column vector
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
j11po = in1(6,:);
j11ro = in1(5,:);
j11yo = in1(7,:);
j12xp = in1(8,:);
j13xp = in1(14,:);
j12zp = in1(10,:);
j13zp = in1(16,:);
q11 = in2(1,:);
q12 = in2(2,:);
t2 = sin(j11po);
t3 = sin(q11);
t4 = cos(j11po);
t5 = cos(j11yo);
t6 = cos(q11);
t7 = sin(j11yo);
t8 = cos(j11ro);
t9 = sin(j11ro);
t10 = t4.^2;
t11 = t7.*t9;
t25 = t2.*t5.*t8;
t12 = t11-t25;
t13 = t2.*t12;
t14 = t5.^2;
t15 = t10.*t14;
t16 = t7.*t8;
t17 = t2.*t5.*t9;
t18 = t16+t17;
t26 = t4.*t7.*t18;
t19 = t13+t15-t26;
t20 = t7.*t9.*t10;
t21 = t2.*t4.*t8;
t22 = t2.*t4.*t5;
t23 = t20+t21+t22;
t24 = cos(q12);
t27 = t6.*t19;
t34 = t3.*t23;
t28 = t27-t34;
t29 = sin(q12);
t30 = t3.*t19;
t31 = t6.*t23;
t32 = t30+t31;
t33 = t24.*t32;
t35 = t28.*t29;
t36 = t33+t35;
t37 = t24.*t28;
t38 = t37-t29.*t32;
t39 = j13zp.*t38;
t40 = t5.*t8;
t42 = t2.*t7.*t9;
t41 = t40-t42;
t43 = t18.*t41;
t44 = t4.*t5.*t18;
t49 = t4.*t9.*t12;
t45 = t43+t44-t49;
t46 = t8.*t9.*t10;
t47 = t4.*t9.*t41;
t51 = t2.*t18;
t48 = t46+t47-t51;
t50 = t6.*t45;
t52 = t3.*t48;
t53 = t50+t52;
t54 = t3.*t45;
t56 = t6.*t48;
t55 = t54-t56;
t57 = t24.*t55;
t58 = t29.*t53;
t59 = t57+t58;
t60 = t24.*t53;
t61 = t60-t29.*t55;
t62 = j13zp.*t61;
t63 = t5.*t9;
t64 = t2.*t7.*t8;
t65 = t63+t64;
t66 = t18.*t65;
t67 = t4.*t8.*t12;
t68 = t4.*t5.*t12;
t69 = t66+t67+t68;
t70 = t8.^2;
t71 = t10.*t70;
t73 = t4.*t9.*t65;
t72 = t13+t71-t73;
t74 = t3.*t72;
t80 = t6.*t69;
t75 = t74-t80;
t76 = t6.*t72;
t77 = t3.*t69;
t78 = t76+t77;
t79 = t24.*t78;
t81 = t79-t29.*t75;
t82 = t24.*t75;
t83 = t29.*t78;
t84 = t82+t83;
joint13PosJaco = reshape([t39-j12xp.*(t2.*t6+t3.*t4.*t5)-j12zp.*(t2.*t3-t4.*t5.*t6)-j13xp.*t36,t62-j12xp.*(t3.*t18-t4.*t6.*t9)+j12zp.*(t6.*t18+t3.*t4.*t9)-j13xp.*t59,-j12xp.*(t3.*t12+t4.*t6.*t8)+j12zp.*(t6.*t12-t3.*t4.*t8)-j13xp.*t81-j13zp.*t84,t39-j13xp.*t36,t62-j13xp.*t59,-j13xp.*t81-j13zp.*t84,0.0,0.0,0.0],[3,3]);
