function gravityTorque = getGravityTorque(in1,in2)
%GETGRAVITYTORQUE
%    GRAVITYTORQUE = GETGRAVITYTORQUE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:24:07

%======================================================================%
% Description: This function computes the gravity torque G of robot dynamics
% gravityTorque = getGravityTorque(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% gravityTorque: Gravity torque of robot dynamics
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
g = in1(1,:);
j11po = in1(6,:);
j11ro = in1(5,:);
j11yo = in1(7,:);
j21po = in1(12,:);
j21ro = in1(11,:);
j21yo = in1(13,:);
l11xp = in1(14,:);
l11zp = in1(16,:);
l21xp = in1(27,:);
l21zp = in1(29,:);
m11 = in1(20,:);
m21 = in1(33,:);
q11 = in2(1,:);
q21 = in2(2,:);
t2 = cos(j11ro);
t3 = cos(q11);
t4 = sin(j11ro);
t5 = sin(j11yo);
t6 = t4.*t5;
t7 = cos(j11yo);
t8 = sin(j11po);
t9 = t6-t2.*t7.*t8;
t10 = cos(j11po);
t11 = sin(q11);
t12 = cos(j21ro);
t13 = cos(q21);
t14 = sin(j21ro);
t15 = sin(j21yo);
t16 = t14.*t15;
t17 = cos(j21yo);
t18 = sin(j21po);
t19 = t16-t12.*t17.*t18;
t20 = cos(j21po);
t21 = sin(q21);
gravityTorque = [-g.*m11.*(l11xp.*(t9.*t11+t2.*t3.*t10)-l11zp.*(t3.*t9-t2.*t10.*t11));-g.*m21.*(l21xp.*(t19.*t21+t12.*t13.*t20)-l21zp.*(t13.*t19-t12.*t20.*t21))];
