function inertiaMatrix = getInertiaMatrix(in1,in2)
%GETINERTIAMATRIX
%    INERTIAMATRIX = GETINERTIAMATRIX(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:24:05

%======================================================================%
% Description: This function computes the inertia matrix M of robot dynamics
% inertiaMatrix = getInertiaMatrix(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% inertiaMatrix: Inertia matrix of robot dynamics
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
j11po = in1(6,:);
j11ro = in1(5,:);
j11yo = in1(7,:);
j21po = in1(12,:);
j21ro = in1(11,:);
j21yo = in1(13,:);
l11xp = in1(14,:);
l11zp = in1(16,:);
l21xp = in1(27,:);
l21zp = in1(29,:);
m11 = in1(20,:);
m21 = in1(33,:);
q11 = in2(1,:);
q21 = in2(2,:);
t2 = conj(j11ro);
t3 = conj(j11yo);
t4 = conj(j11po);
t5 = cos(t2);
t6 = conj(q11);
t7 = cos(t6);
t8 = sin(t2);
t9 = sin(t3);
t10 = t8.*t9;
t11 = cos(t3);
t12 = sin(t4);
t13 = t10-t5.*t11.*t12;
t14 = cos(t4);
t15 = sin(t6);
t16 = cos(j11ro);
t17 = cos(q11);
t18 = sin(j11ro);
t19 = sin(j11yo);
t20 = t18.*t19;
t21 = cos(j11yo);
t22 = sin(j11po);
t23 = t20-t16.*t21.*t22;
t24 = cos(j11po);
t25 = sin(q11);
t26 = conj(l11xp);
t27 = conj(l11zp);
t28 = t5.*t9;
t29 = t8.*t11.*t12;
t30 = t28+t29;
t31 = t16.*t19;
t32 = t18.*t21.*t22;
t33 = t31+t32;
t34 = conj(j21ro);
t35 = conj(j21yo);
t36 = conj(j21po);
t37 = cos(t34);
t38 = conj(q21);
t39 = cos(t38);
t40 = sin(t34);
t41 = sin(t35);
t42 = t40.*t41;
t43 = cos(t35);
t44 = sin(t36);
t45 = t42-t37.*t43.*t44;
t46 = cos(t36);
t47 = sin(t38);
t48 = cos(j21ro);
t49 = cos(q21);
t50 = sin(j21ro);
t51 = sin(j21yo);
t52 = t50.*t51;
t53 = cos(j21yo);
t54 = sin(j21po);
t55 = t52-t48.*t53.*t54;
t56 = cos(j21po);
t57 = sin(q21);
t58 = conj(l21xp);
t59 = conj(l21zp);
t60 = t37.*t41;
t61 = t40.*t43.*t44;
t62 = t60+t61;
t63 = t48.*t51;
t64 = t50.*t53.*t54;
t65 = t63+t64;
inertiaMatrix = reshape([m11.*((l11xp.*(t23.*t25+t16.*t17.*t24)-l11zp.*(t17.*t23-t16.*t24.*t25)).*(t26.*(t13.*t15+t5.*t7.*t14)-t27.*(t7.*t13-t5.*t14.*t15)).*2.0+(l11xp.*(t17.*t22+t21.*t24.*t25)+l11zp.*(t22.*t25-t17.*t21.*t24)).*(t26.*(t7.*t12+t11.*t14.*t15)+t27.*(t12.*t15-t7.*t11.*t14)).*2.0+(l11xp.*(t25.*t33-t17.*t18.*t24)-l11zp.*(t17.*t33+t18.*t24.*t25)).*(t26.*(t15.*t30-t7.*t8.*t14)-t27.*(t7.*t30+t8.*t14.*t15)).*2.0).*(1.0./2.0),0.0,0.0,m21.*((l21xp.*(t55.*t57+t48.*t49.*t56)-l21zp.*(t49.*t55-t48.*t56.*t57)).*(t58.*(t45.*t47+t37.*t39.*t46)-t59.*(t39.*t45-t37.*t46.*t47)).*2.0+(l21xp.*(t49.*t54+t53.*t56.*t57)+l21zp.*(t54.*t57-t49.*t53.*t56)).*(t58.*(t39.*t44+t43.*t46.*t47)+t59.*(t44.*t47-t39.*t43.*t46)).*2.0+(l21xp.*(t57.*t65-t49.*t50.*t56)-l21zp.*(t49.*t65+t50.*t56.*t57)).*(t58.*(t47.*t62-t39.*t40.*t46)-t59.*(t39.*t62+t40.*t46.*t47)).*2.0).*(1.0./2.0)],[2,2]);
