function joint21Vel = getJoint21Velocity(in1,in2)
%GETJOINT21VELOCITY
%    JOINT21VEL = GETJOINT21VELOCITY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:24:04

%======================================================================%
% Description: This function computes the velocity of joint21
% joint21Vel = getJoint21Velocity(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% joint21Vel: Velocity of the joint21 - column vector
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
joint21Vel = [0.0;0.0;0.0];
