function joint11Pos = getJoint11Position(in1,in2)
%GETJOINT11POSITION
%    JOINT11POS = GETJOINT11POSITION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:24:02

%======================================================================%
% Description: This function computes the position of joint11
% joint11Pos = getJoint11Position(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% joint11Pos: Position of the joint11 - column vector
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
j11xp = in1(2,:);
j11yp = in1(3,:);
j11zp = in1(4,:);
joint11Pos = [j11xp;j11yp;j11zp];
