function link21Rot = getLink21Rotation(in1,in2)
%GETLINK21ROTATION
%    LINK21ROT = GETLINK21ROTATION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:24:05

%======================================================================%
% Description: This function computes the rotation matrix of the link21
% link21Rot = getLink21Rotation(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% link21Rot: Rotation matrix of the link21 - 3x3 matrix
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
j21po = in1(12,:);
j21ro = in1(11,:);
j21yo = in1(13,:);
l21po = in1(31,:);
l21ro = in1(30,:);
l21yo = in1(32,:);
q21 = in2(2,:);
t2 = cos(j21po);
t3 = cos(l21po);
t4 = sin(j21po);
t5 = sin(l21ro);
t6 = cos(l21ro);
t7 = sin(l21po);
t8 = sin(j21yo);
t9 = sin(l21yo);
t10 = cos(l21yo);
t11 = cos(j21yo);
t12 = cos(q21);
t13 = t2.*t7.*t11;
t14 = t3.*t4.*t6;
t15 = t2.*t3.*t5.*t8;
t16 = t13+t14+t15;
t17 = sin(q21);
t18 = t5.*t9;
t33 = t6.*t7.*t10;
t19 = t18-t33;
t20 = t4.*t19;
t21 = t6.*t9;
t22 = t5.*t7.*t10;
t23 = t21+t22;
t24 = t2.*t3.*t10.*t11;
t25 = t20+t24-t2.*t8.*t23;
t26 = cos(j21ro);
t27 = sin(j21ro);
t28 = t11.*t26;
t34 = t4.*t8.*t27;
t29 = t28-t34;
t30 = t8.*t26;
t31 = t4.*t11.*t27;
t32 = t30+t31;
t35 = t6.*t10;
t51 = t5.*t7.*t9;
t36 = t35-t51;
t37 = t5.*t10;
t38 = t6.*t7.*t9;
t39 = t37+t38;
t40 = t3.*t5.*t29;
t41 = t2.*t3.*t6.*t27;
t42 = t40+t41-t7.*t32;
t43 = t23.*t29;
t44 = t3.*t10.*t32;
t45 = t43+t44-t2.*t19.*t27;
t46 = t11.*t27;
t47 = t4.*t8.*t26;
t48 = t46+t47;
t49 = t8.*t27;
t52 = t4.*t11.*t26;
t50 = t49-t52;
t53 = t7.*t50;
t54 = t2.*t3.*t6.*t26;
t55 = t53+t54-t3.*t5.*t48;
t56 = t23.*t48;
t57 = t3.*t10.*t50;
t58 = t2.*t19.*t26;
t59 = t56+t57+t58;
link21Rot = reshape([-t16.*t17+t12.*t25,t12.*t45+t17.*t42,t12.*t59-t17.*t55,t4.*t39-t2.*t8.*t36-t2.*t3.*t9.*t11,t29.*t36-t3.*t9.*t32-t2.*t27.*t39,t36.*t48-t3.*t9.*t50+t2.*t26.*t39,t12.*t16+t17.*t25,-t12.*t42+t17.*t45,t12.*t55+t17.*t59],[3,3]);
