function link21Vel = getLink21Velocity(in1,in2)
%GETLINK21VELOCITY
%    LINK21VEL = GETLINK21VELOCITY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Oct-2018 18:24:04

%======================================================================%
% Description: This function computes the velocity of the link21
% link21Vel = getLink21Velocity(physicalParams, stateVariable)
% @Inputs:
% physicalParams: Physical parameters of the dynamical system - column vector
% stateVariable: State variable of the dynamical system - column vector
% @Output:
% link21Vel: Velocity of the link21 - column vector
% Version: 1.0
% Author: Quoc-Viet Dang
%======================================================================%
dq21 = in2(4,:);
j21po = in1(12,:);
j21ro = in1(11,:);
j21yo = in1(13,:);
l21xp = in1(27,:);
l21zp = in1(29,:);
q21 = in2(2,:);
t2 = sin(j21po);
t3 = sin(q21);
t4 = cos(j21po);
t5 = cos(j21yo);
t6 = cos(q21);
t7 = sin(j21ro);
t8 = cos(j21ro);
t9 = sin(j21yo);
t10 = t8.*t9;
t11 = t2.*t5.*t7;
t12 = t10+t11;
t13 = t7.*t9;
t14 = t13-t2.*t5.*t8;
link21Vel = [-dq21.*(l21xp.*(t2.*t6+t3.*t4.*t5)+l21zp.*(t2.*t3-t4.*t5.*t6));-dq21.*(l21xp.*(t3.*t12-t4.*t6.*t7)-l21zp.*(t6.*t12+t3.*t4.*t7));-dq21.*(l21xp.*(t3.*t14+t4.*t6.*t8)-l21zp.*(t6.*t14-t3.*t4.*t8))];
